
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, yy_size_t len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 38
#define YY_END_OF_BUFFER 39
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[302] =
    {   0,
       36,   36,   39,   38,   33,   31,   32,   30,   36,   38,
       36,   34,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,   36,   14,   36,   36,   34,    0,    0,
       35,    0,   35,   35,   35,   35,   35,   35,   35,    6,
       35,   35,   35,    2,   35,   35,   35,   35,   35,   35,
       35,   35,   14,   14,    0,   21,    0,    0,   37,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,    8,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   14,
        0,    0,    0,   35,   35,   35,   35,    3,   35,   35,
       35,    4,   35,   35,   22,   35,   35,   35,   35,   35,

       35,   35,   14,   35,   35,   35,   28,   23,   10,   35,
       35,   35,   35,   35,   35,   35,   35,   35,    5,   35,
       35,   35,   35,   24,   35,   35,   35,   11,   29,    9,
       35,   27,    0,   35,   25,    0,   11,   35,    0,    0,
        0,    0,   26,    0,    0,   35,    0,    0,    0,    0,
        7,    0,    0,    0,    1,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    7,    0,    0,    0,    0,    0,
        1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   17,    0,    0,    0,    0,    0,    0,    0,
       19,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       16,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   18,    0,    0,    0,    0,    0,    0,
        0,    0,   20,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   13,
        0,    0,    0,    0,    0,   12,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   15,

        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    5,    1,    1,    6,
        7,    5,    5,    8,    5,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    1,   12,   13,
       14,   13,    1,    1,   15,   15,   15,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
       15,   15,   16,   15,   15,   15,   15,   15,   15,   15,
       17,    5,   18,    1,    1,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   15,   15,   28,   29,   30,
       31,   32,   15,   33,   34,   35,   36,   37,   38,   15,
       39,   15,   40,    1,   41,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[42] =
    {   0,
        1,    2,    3,    1,    1,    4,    5,    6,    1,    1,
        7,    1,    1,    1,    8,    8,    9,    1,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    1,
        1
    } ;

static const flex_int16_t yy_base[334] =
    {   0,
        0,    0,  927, 1187, 1187, 1187, 1187, 1187,  909,  909,
       33,  904,   41,   43,   44,   46,   49,   43,   58,   66,
       72,   78,   83,  904,  909,  886,   45, 1187,   51,   57,
       84,   70,   95,   96,  101,  107,  112,  115,  125,  126,
      129,  130,  140,  141,  146,  151,  156,  169,  172,  166,
      180,  183,  885,  884,   66, 1187,  210,  107, 1187,  194,
      197,  200,  208,  214,  219,  220,  230,  234,  240,  244,
      245,  263,  272,  273,  258,  266,  269,  272,  277,  876,
      222,  169,  304,  286,  290,  294,  319,  320,  325,  326,
      319,  320,  330,  331,  199,  325,  343,  348,  335,  353,

      363,  364,  866,  369,  305,  374,  249,  281,  377,  385,
      404,  410,  412,  413,  418,  420,  434,  422,  430,  426,
      451,  435,  460,  371,  461,  467,  468,  469,  436,  470,
      477,  486,  813,  487,  489,  494,  495,  496,  503,  504,
      537,  798,  505,  578,  618,  512,  651,  792,  807,  766,
      725,  688,  648,  729,    0,  770,   65,  647,  645,  632,
      621,  618,  611,  617,  574,  513,    0,    0,  531,  521,
      505,  811,    0,  497,  489,  463,  451,  446,  453,  426,
      422,  417,  413,  424,  414,  429,  403,  396,  384,  382,
      405,  373,  364,  396,  384,  364,  351,  347,  353,  329,

      339,  520,  338,   85,  303,  105,  521,  328,  300,  522,
      523,  529,  530,  619,  266,  623,  620,  621,  625,  291,
      627,  628, 1187,  630,  649,  632,  652,  251,  659,  657,
     1187,  660,  664,  674,  667,  675,  824,  677,  828,  684,
     1187,  831,  254,  835,  263,  231,  838,  840,  841,  848,
      851,  853,  854, 1187,  855,  858,  862,  865,  222,  239,
      868,  869, 1187,  873,  875,  877,  883,  239,  231,   72,
      886,  211,  887,  891,  894,  135,   89,  210,  897,  189,
      186,  143,  898,  192,  903,  177,  904,  905,  906,  915,
      922,  924,  932,  935,  943,  163,  119,   99,   63, 1187,

     1187,  956,  964,  971,  978,  985,  992, 1000, 1009, 1017,
     1024, 1031, 1038, 1045, 1052, 1059, 1066, 1073, 1080, 1087,
     1094, 1101, 1108, 1115, 1122, 1129, 1136, 1143, 1151, 1159,
     1167, 1175, 1177
    } ;

static const flex_int16_t yy_def[334] =
    {   0,
      301,    1,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  302,  302,  302,  302,  302,   16,   16,   16,
       16,   16,   16,  301,  303,  301,  301,  301,  301,  304,
       16,  301,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,  303,  303,  304,  301,  305,  301,  301,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,  302,  302,  302,   16,   16,   16,   16,   16,  306,
      301,  304,  305,   20,   20,   20,  302,  302,  302,  302,
       16,   16,   16,   16,  301,   16,   16,   16,   16,   16,

       16,   16,  306,   16,   20,   16,  301,  301,   16,   16,
      302,  302,  302,  302,  302,  302,  302,   16,   16,  302,
      302,   20,  302,  301,  302,  302,  302,  302,  301,  302,
      302,  301,  301,  302,  301,  307,  302,  302,  301,  301,
      301,  301,  301,  301,  301,  302,  301,  301,  308,  141,
      308,  301,  301,  301,  154,  301,  147,  301,  301,  301,
      301,  301,  301,  301,  308,  308,  141,  152,  301,  309,
      309,  154,  156,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  310,  301,  301,  301,  301,  311,  301,

      301,  312,  313,  301,  301,  301,  314,  301,  315,  301,
      316,  312,  317,  301,  301,  301,  301,  318,  314,  319,
      320,  316,  301,  321,  301,  322,  317,  301,  301,  318,
      301,  323,  324,  301,  325,  320,  301,  316,  321,  322,
      301,  326,  301,  301,  301,  301,  301,  318,  323,  301,
      327,  324,  325,  301,  328,  301,  322,  326,  301,  329,
      301,  327,  301,  330,  301,  325,  328,  301,  329,  329,
      301,  301,  301,  327,  330,  313,  329,  331,  317,  329,
      331,  331,  317,  331,  317,  331,  317,  322,  326,  326,
      326,  326,  326,  326,  332,  333,  333,  301,  301,  301,

        0,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301
    } ;

static const flex_int16_t yy_nxt[1229] =
    {   0,
        4,    4,    4,    4,    5,    6,    7,    8,    9,   10,
       11,    8,   12,    5,   13,   14,    4,    4,   13,   15,
       16,   17,   18,   19,   13,   13,   20,   13,   13,   13,
       13,   21,   13,   22,   13,   13,   13,   23,   13,    6,
        7,   26,   29,   27,   29,   29,   30,   29,   30,   30,
       29,   30,   29,   26,   30,   27,   30,   32,   55,   32,
       32,   31,   32,   56,   37,   32,  157,   55,   31,  300,
       41,   38,  301,   39,   35,  270,   31,   33,  277,   40,
       58,   34,   36,   31,   31,   42,  214,   59,   43,   44,
       31,   31,  270,   31,   45,   46,   31,   31,  158,   31,

      280,   31,   31,   49,   47,   31,  216,   48,   52,   31,
       31,   31,   50,   31,   31,   51,  299,   58,  158,   31,
       31,   31,   31,   31,   59,   31,   31,   60,   31,   61,
       31,   62,   31,   65,   31,  298,  276,   31,  158,   31,
       31,   63,   31,   66,   31,   64,  282,   31,   31,  284,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       69,   67,   68,  279,   31,   31,   31,   31,   31,   31,
       55,   31,   70,   31,   31,   56,   31,   71,   31,  298,
      282,   31,   73,   31,   77,   72,   74,   31,   75,  282,
       31,   31,  270,   31,   31,  282,   31,   31,   31,   31,

       95,   31,   76,  286,   30,   31,   78,   31,   31,   79,
       31,   81,   31,  282,  278,   31,   56,   82,   31,   31,
       84,   31,   31,   81,   31,   31,   31,   86,   56,   82,
       87,   85,   31,   31,  270,   31,   88,   31,   31,   31,
      276,   31,  270,  268,   31,   31,   31,   31,   31,   91,
      107,   89,   31,   90,   30,   31,   92,   31,   93,   31,
      261,   31,   31,   31,   95,   31,  260,   31,   30,   31,
       31,   31,   31,   29,   29,   94,   31,   30,   30,   32,
      259,  243,  108,   31,   31,   98,   30,   31,   32,   32,
       31,   31,  220,   31,   31,   31,   31,   31,   99,   31,

      229,  209,   31,  100,  102,   81,  101,   97,   96,   31,
       56,   82,  105,   31,   31,  104,  106,   31,   31,   31,
      107,   29,   31,   31,   30,   30,  108,   29,   31,  220,
       30,   30,  215,  121,   31,   32,   32,   31,   31,  203,
      209,   32,   32,  113,   31,   31,  110,   31,   31,   31,
       31,  208,   31,   31,  199,   31,   31,   31,   31,  109,
       31,   31,   31,  112,  111,  114,   31,  206,   31,  116,
       31,   31,  124,   31,  115,   31,   30,  205,   31,  117,
       31,   31,   31,  118,  204,  203,  119,   31,   31,   31,
       31,   31,  122,  120,   31,   31,   31,  194,  201,   31,

      200,   31,   31,   31,   31,  124,  199,  123,  198,   30,
       31,   29,   31,   29,   29,   30,  197,   30,   30,   29,
       32,  129,  196,   30,  195,   30,   32,  132,   32,   32,
      194,   30,  193,  127,   32,   29,   32,  129,  128,   30,
       31,   30,   32,  192,  125,  191,  126,  131,   31,   31,
       32,  190,   29,  189,  130,   31,   30,   31,   31,  133,
      188,  135,  136,   31,  134,   30,   30,   32,   29,   29,
      139,   29,   30,   30,   30,   30,   32,   32,  140,  187,
      186,  185,  141,   32,   32,   32,   32,  132,  143,  137,
      135,   30,   30,   32,   30,   29,  145,   29,  184,   30,

       30,   30,  138,   32,  147,  140,  143,  183,   30,  141,
       30,   32,   32,   29,  166,  182,  171,   30,  146,  151,
      167,  210,  217,  210,  222,  211,  218,  211,   32,  223,
      210,  225,  171,  137,  211,  226,  148,  149,  150,  181,
      149,  149,  149,  151,  149,  149,  149,  149,  149,  149,
      149,  152,  152,  149,  149,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  149,  149,  154,  154,
      165,  154,  154,  154,  154,  154,  154,  154,  154,  155,
      154,  154,  156,  156,  154,  154,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  154,  154,  157,
      214,  217,  230,   30,  216,  218,  217,  231,  234,  222,
      218,  237,  235,  240,  301,  180,  223,  238,  241,  159,
      160,  179,  161,  159,  160,  162,  161,  178,  177,  162,
      225,  158,  147,  225,  226,  228,   30,  226,  230,  163,
      244,  247,  176,  301,  245,  250,  231,  248,  253,  251,
      175,  159,  160,  254,  161,  234,  234,  162,  222,  235,
      235,  174,  169,  223,  148,  240,  246,  163,  149,  166,
      301,  149,  149,  149,  151,  167,  149,  149,  168,  149,

      149,  149,  168,  168,  149,  149,  168,  168,  168,  168,
      168,  168,  168,  168,  168,  168,  168,  168,  168,  168,
      168,  168,  168,  168,  168,  168,  168,  149,  149,  170,
      170,  165,  170,  170,  170,  170,  170,  170,  170,  170,
      171,  170,  170,  172,  172,  170,  170,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  172,  172,  172,  170,  170,
      154,  154,  165,  154,  154,  154,  154,  154,  154,  154,
      154,  155,  154,  154,  173,  173,  154,  154,  173,  173,
      173,  173,  173,  173,  173,  173,  173,  173,  173,  173,

      173,  173,  173,  173,  173,  173,  173,  173,  173,  154,
      154,  154,  154,  165,  154,  154,  154,  154,  154,  154,
      154,  154,  155,  154,  154,  237,  164,  154,  154,  237,
      223,  238,  256,  153,  223,  238,  244,  241,  257,  247,
      245,  230,  247,  142,  231,  248,  231,  231,  248,  250,
      154,  154,  262,  251,  250,  253,  265,  263,  251,  256,
      301,  254,  266,  240,  241,  257,  256,   80,  241,  271,
      262,  241,  257,  272,  273,  301,  265,   80,  253,  263,
      274,  254,  266,  254,  265,   80,   53,  271,  273,  254,
      266,  272,  262,  263,  274,  273,   24,  263,  225,  225,

      263,  274,  226,  226,  225,  225,  240,  256,  226,  288,
       53,  241,  241,  257,   24,  283,  256,   28,   25,   24,
      289,  241,  257,  256,  285,  256,  301,  301,  241,  257,
      241,  257,  287,  256,  301,  301,  295,  301,  241,  257,
      290,  241,  257,  301,  295,  301,  301,  291,  292,  241,
      257,  301,  301,  293,  301,  301,  294,   31,  301,   31,
      301,  301,   31,   31,   31,   54,  301,  301,  301,  301,
      301,   54,   57,  301,  301,   57,  301,  301,   57,   83,
      301,  301,   83,   83,   83,   83,  103,  301,  301,  301,
      301,  301,  103,  144,  301,  144,  301,  301,  301,  144,

      149,  149,  301,  149,  149,  149,  149,  149,  149,  170,
      170,  301,  170,  170,  170,  170,  170,  170,  202,  301,
      301,  301,  301,  301,  202,  207,  301,  301,  301,  301,
      301,  207,  212,  301,  212,  301,  301,  212,  212,  213,
      301,  301,  301,  301,  301,  213,  219,  301,  219,  301,
      301,  219,  219,  221,  301,  301,  301,  301,  301,  221,
      224,  301,  301,  224,  301,  301,  224,  227,  301,  227,
      301,  301,  227,  227,  232,  301,  301,  232,  301,  301,
      232,  233,  301,  301,  301,  301,  301,  233,  236,  301,
      236,  301,  301,  236,  236,  239,  301,  301,  239,  239,

      239,  239,  242,  301,  301,  242,  301,  301,  242,  249,
      301,  301,  249,  249,  249,  249,  252,  301,  252,  301,
      301,  252,  252,  255,  301,  301,  255,  301,  301,  255,
      258,  301,  301,  258,  258,  258,  258,  264,  301,  301,
      264,  301,  301,  264,  267,  301,  301,  267,  267,  267,
      267,  269,  269,  301,  269,  269,  269,  269,  269,  269,
      275,  301,  301,  275,  275,  275,  275,  281,  281,  301,
      281,  281,  281,  281,  281,  281,  296,  301,  301,  296,
      296,  301,  296,  297,  297,  297,    3,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301
    } ;

static const flex_int16_t yy_chk[1229] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   11,   13,   11,   14,   15,   13,   16,   14,   15,
       17,   16,   29,   27,   17,   27,   29,   13,   30,   14,
       15,   18,   16,   30,   16,   17,  157,   55,   18,  299,
       18,   16,   55,   16,   15,  270,   19,   14,  270,   17,
       32,   14,   15,   19,   20,   19,  204,   32,   19,   20,
       21,   20,  277,   20,   20,   20,   22,   21,  157,   21,

      277,   23,   31,   22,   21,   22,  206,   21,   23,   31,
       23,   31,   22,   33,   34,   22,  298,   58,  204,   35,
       33,   34,   33,   34,   58,   36,   35,   33,   35,   34,
       37,   35,   36,   38,   36,  297,  276,   37,  206,   37,
       38,   36,   38,   39,   40,   37,  282,   41,   42,  282,
       39,   40,   39,   40,   41,   42,   41,   42,   43,   44,
       42,   40,   41,  276,   45,   43,   44,   43,   44,   46,
       82,   45,   43,   45,   47,   82,   46,   45,   46,  296,
      286,   47,   47,   47,   50,   46,   47,   48,   48,  281,
       49,   50,  280,   50,   48,  284,   48,   49,   51,   49,

       95,   52,   49,  284,   95,   51,   51,   51,   52,   52,
       52,   57,   60,  278,  272,   61,   57,   57,   62,   60,
       60,   60,   61,   81,   61,   62,   63,   62,   81,   81,
       63,   61,   64,   63,  269,   63,   64,   65,   66,   64,
      268,   64,  260,  259,   65,   66,   65,   66,   67,   67,
      107,   65,   68,   66,  107,   67,   68,   67,   69,   68,
      246,   68,   70,   71,   72,   69,  245,   69,   72,   70,
       71,   70,   71,   73,   74,   71,   75,   73,   74,   72,
      243,  228,  108,   75,   76,   75,  108,   77,   73,   74,
       78,   76,  220,   76,   77,   79,   77,   78,   76,   78,

      215,  209,   79,   77,   79,   83,   78,   74,   73,   84,
       83,   83,   85,   85,   84,   84,   86,   86,   85,   85,
       87,   88,   86,   86,   87,   88,   89,   90,  105,  208,
       89,   90,  205,  105,  105,   87,   88,   91,   92,  203,
      201,   89,   90,   96,   91,   92,   91,   92,   93,   94,
       96,  200,   96,   99,  199,   93,   94,   93,   94,   90,
       99,   97,   99,   94,   93,   97,   98,  198,   97,   99,
       97,  100,  124,   98,   98,   98,  124,  197,  100,  100,
      100,  101,  102,  101,  196,  195,  102,  104,  101,  102,
      101,  102,  106,  104,  104,  109,  104,  194,  193,  106,

      192,  106,  109,  110,  109,  111,  191,  110,  190,  111,
      110,  112,  110,  113,  114,  112,  189,  113,  114,  115,
      111,  116,  188,  115,  187,  116,  112,  120,  113,  114,
      186,  120,  185,  114,  115,  117,  116,  129,  115,  117,
      118,  129,  120,  184,  112,  183,  113,  118,  119,  118,
      117,  182,  121,  181,  117,  119,  121,  119,  122,  121,
      180,  123,  125,  122,  122,  123,  125,  121,  126,  127,
      128,  130,  126,  127,  128,  130,  123,  125,  131,  179,
      178,  177,  131,  126,  127,  128,  130,  132,  134,  126,
      135,  132,  134,  131,  135,  136,  137,  138,  176,  136,

      137,  138,  127,  134,  139,  140,  143,  175,  139,  140,
      143,  137,  138,  146,  166,  174,  171,  146,  138,  166,
      166,  202,  207,  210,  211,  202,  207,  210,  146,  211,
      212,  213,  170,  146,  212,  213,  139,  141,  141,  169,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  144,  144,
      165,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,

      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  145,
      214,  217,  218,  145,  216,  217,  219,  218,  221,  222,
      219,  224,  221,  226,  222,  164,  224,  224,  226,  214,
      214,  163,  214,  216,  216,  214,  216,  162,  161,  216,
      225,  145,  147,  227,  225,  214,  147,  227,  230,  216,
      229,  232,  160,  230,  229,  233,  232,  232,  235,  233,
      159,  147,  147,  235,  147,  234,  236,  147,  238,  234,
      236,  158,  153,  238,  147,  240,  229,  147,  152,  152,
      240,  152,  152,  152,  152,  152,  152,  152,  152,  152,

      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  152,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  154,
      154,  151,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      156,  156,  150,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,

      156,  156,  156,  156,  156,  156,  156,  156,  156,  156,
      156,  172,  172,  149,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  172,  237,  148,  172,  172,  239,
      237,  237,  242,  142,  239,  239,  244,  242,  242,  247,
      244,  248,  249,  133,  247,  247,  248,  249,  249,  250,
      172,  172,  251,  250,  252,  253,  255,  251,  252,  256,
      253,  255,  255,  257,  256,  256,  258,  103,  257,  261,
      262,  258,  258,  261,  264,  262,  265,   80,  266,  264,
      264,  265,  265,  266,  267,   54,   53,  271,  273,  267,
      267,  271,  274,  273,  273,  275,   26,  274,  279,  283,

      275,  275,  279,  283,  285,  287,  288,  289,  285,  287,
       25,  288,  289,  289,   24,  279,  290,   12,   10,    9,
      288,  290,  290,  291,  283,  292,    3,    0,  291,  291,
      292,  292,  285,  293,    0,    0,  294,    0,  293,  293,
      289,  294,  294,    0,  295,    0,    0,  290,  291,  295,
      295,    0,    0,  292,    0,    0,  293,  302,    0,  302,
        0,    0,  302,  302,  302,  303,    0,    0,    0,    0,
        0,  303,  304,    0,    0,  304,    0,    0,  304,  305,
        0,    0,  305,  305,  305,  305,  306,    0,    0,    0,
        0,    0,  306,  307,    0,  307,    0,    0,    0,  307,

      308,  308,    0,  308,  308,  308,  308,  308,  308,  309,
      309,    0,  309,  309,  309,  309,  309,  309,  310,    0,
        0,    0,    0,    0,  310,  311,    0,    0,    0,    0,
        0,  311,  312,    0,  312,    0,    0,  312,  312,  313,
        0,    0,    0,    0,    0,  313,  314,    0,  314,    0,
        0,  314,  314,  315,    0,    0,    0,    0,    0,  315,
      316,    0,    0,  316,    0,    0,  316,  317,    0,  317,
        0,    0,  317,  317,  318,    0,    0,  318,    0,    0,
      318,  319,    0,    0,    0,    0,    0,  319,  320,    0,
      320,    0,    0,  320,  320,  321,    0,    0,  321,  321,

      321,  321,  322,    0,    0,  322,    0,    0,  322,  323,
        0,    0,  323,  323,  323,  323,  324,    0,  324,    0,
        0,  324,  324,  325,    0,    0,  325,    0,    0,  325,
      326,    0,    0,  326,  326,  326,  326,  327,    0,    0,
      327,    0,    0,  327,  328,    0,    0,  328,  328,  328,
      328,  329,  329,    0,  329,  329,  329,  329,  329,  329,
      330,    0,    0,  330,  330,  330,  330,  331,  331,    0,
      331,  331,  331,  331,  331,  331,  332,    0,    0,  332,
      332,    0,  332,  333,  333,  333,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "JAVA.l"
#line 2 "JAVA.l"
#include<string.h>
   int i,m;
   struct symtab
   {
     char name[200];
     char type[200];
   }sym[20];
	FILE* yyin;	
	int checksymtab(char *temp);
#line 828 "lex.yy.c"
#line 829 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			yy_size_t yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 24 "JAVA.l"


#line 1049 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 302 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1187 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 26 "JAVA.l"
{printf("\n%s : Preprocessor directive to include header files",yytext);}
	YY_BREAK
case 2:
#line 29 "JAVA.l"
case 3:
#line 30 "JAVA.l"
case 4:
#line 31 "JAVA.l"
case 5:
#line 32 "JAVA.l"
case 6:
#line 33 "JAVA.l"
case 7:
#line 34 "JAVA.l"
case 8:
#line 35 "JAVA.l"
case 9:
#line 36 "JAVA.l"
case 10:
YY_RULE_SETUP
#line 36 "JAVA.l"
{printf("\n %s : Keyword",yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 38 "JAVA.l"
{printf("\n %s : Access Specifier", yytext);}
	YY_BREAK
case 12:
#line 42 "JAVA.l"
case 13:
YY_RULE_SETUP
#line 42 "JAVA.l"
{printf("\n %s : Library Function",yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 44 "JAVA.l"
{printf("\n %s : This is single line comment", yytext);}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 46 "JAVA.l"
{printf("\n%s : Defination of JAVA main function",yytext);}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "JAVA.l"
{
									printf("\n%s : Definition of function with return type void" ,yytext);
									if(checksymtab(yytext) == 0) {
										strcpy(sym[m].name,yytext);
										strcpy(sym[m].type,"Function");
										m++;
									}
								}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "JAVA.l"
{printf("\n%s : Definition of function with return type int" ,yytext);}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "JAVA.l"
{printf("\n%s : Definition of function with return type char" ,yytext);}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "JAVA.l"
{printf("\n%s : Definition of function with return type float" ,yytext);}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "JAVA.l"
{printf("\n%s : Definition of function with return type double" ,yytext);}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 61 "JAVA.l"
{printf("\n%s : Function call" ,yytext);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "JAVA.l"
{printf("\n%s : Declaration of integer variables",yytext);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "JAVA.l"
{printf("\n%s : Declaration of character variables",yytext);}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "JAVA.l"
{printf("\n%s : Declaration of float variables",yytext);}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "JAVA.l"
{printf("\n%s : Declaration of double variables",yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "JAVA.l"
{printf("\n%s : Declaration of boolean variables",yytext);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "JAVA.l"
{printf("\n%s : Declaration of string variables",yytext);}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "JAVA.l"
{printf("\n%s : Declaration of byte variables",yytext);}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "JAVA.l"
{printf("\n%s : Declaration of short variables",yytext);}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 72 "JAVA.l"
{}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 73 "JAVA.l"
{printf("\n %s : Opening brace",yytext);}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 74 "JAVA.l"
{printf("\n %s : Closing brace",yytext);}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 77 "JAVA.l"
{printf("\n %s : Arithmetic operator",yytext);}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 78 "JAVA.l"
{printf("\n %s : Relational operator",yytext);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 80 "JAVA.l"
{
		printf("\n %s : Identifier",yytext);
		if(checksymtab(yytext) == 0) {
			strcpy(sym[m].name,yytext);
			strcpy(sym[m].type,"Identifier");
			m++;
		}
	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "JAVA.l"
{
				printf("\n %s : Arithmetic number",yytext);
				if(checksymtab(yytext) == 0) {
					strcpy(sym[m].name,yytext);
					strcpy(sym[m].type,"Number");
					m++;
				}
			}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 98 "JAVA.l"
{
				printf("\n %s : Array",yytext);
				if(checksymtab(yytext) == 0) {
					strcpy(sym[m].name,yytext);
					strcpy(sym[m].type,"Array");
					m++;
				}
			}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 107 "JAVA.l"
ECHO;
	YY_BREAK
#line 1297 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 302 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 302 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 301);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        yy_size_t yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 107 "JAVA.l"


int checksymtab(char *temp) {
	for(int i = 0; i < 20; i++) 
		if(strcmp(sym[i].name, temp) == 0) return 1;
 	return 0;
}
int main(int argc,char* argv[])
{

/*	printf("Enter the String: ");
	yylex();*/
	
	yyin=fopen(argv[1],"r");
	yylex();
	fclose(yyin);


 	printf("\n\n\n\t--------------------\n");
 	printf("\tIndex\tSymbol name\t\t\tSymbol Type");
 	printf("\t\t\n--------------------------\n");

 	for(i=0;i<m;i++)
 	{
	    printf("\n\t%d",i+1);
 		printf("\t\t%s",sym[i].name);
  		printf("\t\t\t%s\n",sym[i].type);
	}
 	yywrap();
}

extern int yywrap()
{
	return 1;
}
